### ISSUE TITLE
Missing dimensions for heat block and PCB thickness

### ISSUE THREAD

**Issue by JamesHagerman** [GaudiLabs/PocketPCR#1]
Hi there,

I would love to build one of these, but I need the dimensions of the aluminum heat block and the thickness of the bottom heater board.

Can you please share that information?

Thanks!

**Comment by abusakib** [comment]
![pcr_3d](https://user-images.githubusercontent.com/21017059/80335928-9aee0f80-8877-11ea-8b1b-020f78d8c2dd.png)
Successfully converted this kicad file to pcb 
contact with me if you want that

**Comment by JamesHagerman** [comment]
@abusakib You don't really need to post a reply to every GitHub issue to get the point across.

Besides, this design requires 3 PCBs, 2 of which require aluminum substrates instead of regular FR4. It's easy enough to load the KiCad files from this repo into PCBWay and place an order... but the Al substrate boards are honestly prohibitively expensive unless you're sourcing them in bulk.

That said, the dimensions I was looking for were committed on March 18 so I'm going to close this issue! Thank you @GaudiLabs for all your work on this!

https://github.com/GaudiLabs/PocketPCR/blob/master/Parts/PocketPCRHeater_V1.PDF
