### ISSUE TITLE
Alternating blank lines on LCD Display

### ISSUE THREAD

**Issue by vektorious** [GaudiLabs/PocketPCR#4]
Thanks for this amazing little thing! I already did some runs and I'm more than happy with the results.

However, I have some problems with my OLED display. It appears like every second line is missing/blank. This makes it hard to read the numbers and I often had to go back to zero and count upwards (pictures attached) to set temps and times.

From what I found by searching for this problem online was that it might be a software/driver problem. What do you think?

![IMG_20200422_084346](https://user-images.githubusercontent.com/20026476/80061269-1b87d580-8531-11ea-97b4-8ec5d6a065c1.jpg)
![IMG_20200422_085925](https://user-images.githubusercontent.com/20026476/80061276-204c8980-8531-11ea-9b97-f79e9a48c2a3.jpg)

**Comment by GaudiLabs** [comment]
Hi Alexander

I am sorry for that. I dont think its software. I think it must be a problem with the display connector. Try if you can re-plug the flat cable that goes to the connector on the backside of the board. Or then I will send you a new board. 


Best, 
Urs



On 23 April 2020 07:15:05 CEST, Alexander Kutschera <notifications@github.com> wrote:
>Thanks for this amazing little thing! I already did some runs and I'm
>more than happy with the results.
>
>However, I have some problems with my OLED display. It appears like
>every second line is missing/blank. This makes it hard to read the
>numbers and I often had to go back to zero and count upwards (pictures
>attached) to set temps and times.
>
>From what I found by searching for this problem online was that it
>might be a software/driver problem. What do you think?
>
>![IMG_20200422_084346](https://user-images.githubusercontent.com/20026476/80061269-1b87d580-8531-11ea-97b4-8ec5d6a065c1.jpg)
>![IMG_20200422_085925](https://user-images.githubusercontent.com/20026476/80061276-204c8980-8531-11ea-9b97-f79e9a48c2a3.jpg)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/PocketPCR/issues/4

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vektorious** [comment]
Hey Urs,

I tried un- and re-plugging the display and did not see any improvement. But, I saw that some connector pins are soldered together (accidentally?). That's probably the cause of the problem. I have to find some desoldering wick and try to fix it. What do you think?

Thanks for the help!

Alex

![IMG_20200425_065008](https://user-images.githubusercontent.com/20026476/80274106-524c2000-86d8-11ea-99b3-150cd36e682d.jpg)

**Comment by GaudiLabs** [comment]
Sure, resoldering the connector pins will probably fix it. Try also to retouch the other ones as there might be a pin not properly soldered. And dont worry if anything goes wrong, a new board is ready to be shipped to you here.

Urs

On 25 April 2020 09:44:02 CEST, Alexander Kutschera <notifications@github.com> wrote:
>Hey Urs,
>
>I tried un- and re-plugging the display and did not see any
>improvement. But, I saw that some connector pins are soldered together
>(accidentally?). That's probably the cause of the problem. I have to
>find some desoldering wick and try to fix it. What do you think?
>
>Thanks for the help!
>
>Alex
>
>![IMG_20200425_065008](https://user-images.githubusercontent.com/20026476/80274106-524c2000-86d8-11ea-99b3-150cd36e682d.jpg)
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/PocketPCR/issues/4#issuecomment-619337060

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vektorious** [comment]
Hey Urs,

I tried hard but so far, I could not resolder the pins. I afraid I have to make use of your offer...
Should I send you my contact details via mail?

Thanks in advance!

Alex
