### ISSUE TITLE
uploading/modifying code

### ISSUE THREAD

**Issue by aaron4444** [GaudiLabs/PocketPCR#7]
Hi. just received mine and i was hoping to make a small modification. Could i ask for maybe a quick few lines on how to upload the modified code with arduino?

**Comment by aaron4444** [comment]
sorry, i also see that the current code version is 1.2.2020, can i ask for the most recent version? thank you again for your time.

**Comment by GaudiLabs** [comment]
Hi

Nice, what modification do you plan to do? The PocketPCR is compatibe with the Adafruit Feather M0. So you can see here how to install the board in the Arduino IDE:

https://learn.adafruit.com/adafruit-feather-m0-basic-proto/

Good Luck,
Urs

On 17 November 2020 02:57:46 CET, aaron4444 <notifications@github.com> wrote:
>Hi. just received mine and i was hoping to make a small modification.
>Could i ask for maybe a quick few lines on how to upload the modified
>code with arduino? 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/GaudiLabs/PocketPCR/issues/7

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aaron4444** [comment]
hi. thank you for your response. 

-  i wanted to be able to give it a recipe that has more steps than typical PCR. so i want to give it steps like 50, 49.5, 49, 48.5 etc. down to room temp. I figure i add a menu item to read a recipe? usually its a start point and an endpoint with a ramp typically between 1 and 0.2 degrees per step. 
 
- I would like to setup serial communication with the computer, to take commands like: heat to this temp.

the next ones are kinda outside of pcr a little. i do dna crytal growth, so i have a camera that i want to do in situ microscopy with. I can see em growing so i was planning to try to trigger from the pocketpcr when it reaches the right temperature to take a picture, or a series of pictures.

**Comment by aaron4444** [comment]
Sorry if this isn't the place to debug. Can't seem to get the ssd1306 library to work. Can you share the version of that library you are using? 


**PocketPCR_V2_quite_dev_i:76:74: error: call of overloaded 'Adafruit_SSD1306(int, int, int, int, int)' is ambiguous**
   76 | Adafruit_SSD1306 display( OLED_MOSI,OLED_CLK,OLED_DC, OLED_RESET, OLED_CS);
      |                                                                          ^
In file included from C:\Users\Aaron-Crucial-2016\Downloads\PocketPCR-master (1)\PocketPCR-master\code\PocketPCR_V2_quite_dev_i\PocketPCR_V2_quite_dev_i.ino:13:
C:\Users\Aaron-Crucial-2016\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:138:3: note: candidate: 'Adafruit_SSD1306::Adafruit_SSD1306(int8_t, int8_t, int8_t, int8_t, int8_t)'
  138 |   Adafruit_SSD1306(int8_t mosi_pin, int8_t sclk_pin, int8_t dc_pin,
      |   ^~~~~~~~~~~~~~~~
C:\Users\Aaron-Crucial-2016\Documents\Arduino\libraries\Adafruit_SSD1306/Adafruit_SSD1306.h:129:3: note: candidate: 'Adafruit_SSD1306::Adafruit_SSD1306(uint8_t, uint8_t, TwoWire*, int8_t, uint32_t, uint32_t)'
  129 |   Adafruit_SSD1306(uint8_t w, uint8_t h, TwoWire *twi = &Wire,
      |   ^~~~~~~~~~~~~~~~
Multiple libraries were found for "Adafruit_ZeroDMA.h"
 Used: C:\Users\Aaron-Crucial-2016\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.6.4\libraries\Adafruit_ZeroDMA
 Not used: C:\Users\Aaron-Crucial-2016\Documents\Arduino\libraries\Adafruit_Zero_DMA_Library
exit status 1
call of overloaded 'Adafruit_SSD1306(int, int, int, int, int)' is ambiguous

**Comment by GaudiLabs** [comment]
Had used an older version of the Adafruit Display Library. Fixed that, just this line that changed:
Adafruit_SSD1306 display(SCREEN_WIDTH, SCREEN_HEIGHT, OLED_MOSI, OLED_CLK, OLED_DC, OLED_RESET, OLED_CS);

Now the current Adafruit_SSD1306 Library should be good to go:
https://github.com/adafruit/Adafruit_SSD1306
